title: El peor blog de la historia
author: Pastelman 
email: your-email@domain.com
description: >
  Quiero terminar con esto de una vez joer!!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
